### ISSUE TITLE
Akemi - Lenovo Chromebook flex 5

### ISSUE THREAD

**Issue by BilalChouaibi** [cb-linux/breath#8] opened 2021-12-20 19:52 UTC
I need help 😭
My touchscreen/sd card slot/sound doesn't work

**Comment by MilkyDeveloper** [comment] 2021-12-22 16:46
Could you boot into ChromeOS, enter crosh (CTRL+ALT+T), and then type in `shell`? Then, post the output of `lspci` and `lsmod`.

**Comment by BilalChouaibi** [comment] 2021-12-22 17:41
### lspci
00:00.0 Host bridge: Intel Corporation Device 9b61 (rev 0c)
00:02.0 VGA compatible controller: Intel Corporation Device 9b41 (rev 02)
00:04.0 Signal processing controller: Intel Corporation Device 1903 (rev 0c)
00:08.0 System peripheral: Intel Corporation Sky Lake Gaussian Mixture Model
00:12.0 Signal processing controller: Intel Corporation Device 02f9
00:14.0 USB controller: Intel Corporation Device 02ed
00:14.2 RAM memory: Intel Corporation Device 02ef
00:14.3 Network controller: Intel Corporation Device 02f0
00:14.5 SD Host controller: Intel Corporation Device 02f5
00:15.0 Serial bus controller [0c80]: Intel Corporation Device 02e8
00:15.1 Serial bus controller [0c80]: Intel Corporation Device 02e9
00:17.0 SATA controller: Intel Corporation Device 02d3
00:19.0 Serial bus controller [0c80]: Intel Corporation Device 02c5
00:1d.0 PCI bridge: Intel Corporation Device 02b0 (rev f0)
00:1e.0 Communication controller: Intel Corporation Device 02a8
00:1e.2 Serial bus controller [0c80]: Intel Corporation Device 02aa
00:1f.0 ISA bridge: Intel Corporation Device 0284
00:1f.3 Multimedia audio controller: Intel Corporation Device 02c8
00:1f.4 SMBus: Intel Corporation Device 02a3
00:1f.5 Serial bus controller [0c80]: Intel Corporation Device 02a4
01:00.0 Non-Volatile memory controller: Samsung Electronics Co Ltd Device a809

### lsmod
![Screenshot 2021-12-22 18 39 30](https://user-images.githubusercontent.com/84464698/147133595-92817774-5011-4fce-85f4-9d563a39df83.png)
![Screenshot 2021-12-22 18 40 39](https://user-images.githubusercontent.com/84464698/147133607-02c0582b-4829-4485-929e-ba7be695cb4d.png)

**Comment by MilkyDeveloper** [comment] 2021-12-23 15:08
Please follow the instructions [here](https://github.com/MilkyDeveloper/cb-linux/issues/3#issuecomment-1000362157).

**Comment by BilalChouaibi** [comment] 2021-12-24 18:20
> Please follow the instructions [here](https://github.com/MilkyDeveloper/cb-linux/issues/3#issuecomment-1000362157).

Its not working for me (touchscreen/sd card slot/audio and bluetooth not working)

**Comment by BilalChouaibi** [comment] 2021-12-24 18:21
Sorry but its not working for me ( touchscreen/sd card slot/ bluetooth and audio)

**Comment by MilkyDeveloper** [comment] 2021-12-24 18:26
Could you give the output of `dmesg` (in a text file) and `lsmod`

**Comment by BilalChouaibi** [comment] 2021-12-24 18:27
Okay thanks

**Comment by BilalChouaibi** [comment] 2021-12-24 21:14
[dmesg.txt](https://github.com/MilkyDeveloper/cb-linux/files/7775147/dmesg.txt)
[lsmod.txt](https://github.com/MilkyDeveloper/cb-linux/files/7775148/lsmod.txt)

**Comment by MilkyDeveloper** [comment] 2021-12-24 21:32
Try running `speaker-test` and post the output here. I can't see any errors in the `dmesg`.

**Comment by BilalChouaibi** [comment] 2021-12-24 21:50
[dmesg.txt](https://github.com/MilkyDeveloper/cb-linux/files/7775169/dmesg.txt)
[speaker-test.txt](https://github.com/MilkyDeveloper/cb-linux/files/7775170/speaker-test.txt)
this time I have executed dmesg and spaker-test inside breath

**Comment by MilkyDeveloper** [comment] 2021-12-24 21:53
Try running lsmod in Breath.

**Comment by BilalChouaibi** [comment] 2021-12-24 21:53
I Can't nothing return

**Comment by BilalChouaibi** [comment] 2021-12-24 21:55
And for aplay -l 
It Say 
aplay: device_list:276: no soundcards found...

**Comment by MilkyDeveloper** [comment] 2021-12-24 21:57
The exact command `lsmod` doesn't return anything? If so, it seems like Breath didn't install correctly. Try completely reinstalling it on your Linux PC (not chromebook).

**Comment by BilalChouaibi** [comment] 2021-12-24 21:57
Ok

**Comment by tikverdev** [comment] 2021-12-30 05:24
I'm running the same Chromebook and everything else works other than the sound. I installed Breath with Ubuntu 21.04 as said [here](https://github.com/MilkyDeveloper/cb-linux/issues/3#issuecomment-1000362157), ran updates and `sof-setup-audio`.

`aplay -l` returns
aplay: device_list:276: no soundcards found...

Here are my other commands if they are needed:
[dmesg.txt](https://github.com/MilkyDeveloper/cb-linux/files/7791587/dmesg.txt)
[lsmod.txt](https://github.com/MilkyDeveloper/cb-linux/files/7791589/lsmod.txt)
[speaker-test.txt](https://github.com/MilkyDeveloper/cb-linux/files/7791591/speaker-test.txt)

**Comment by BilalChouaibi** [comment] 2021-12-30 07:46
> I'm running the same Chromebook and everything else works other than the sound. I installed Breath with Ubuntu 21.04 as said [here](https://github.com/MilkyDeveloper/cb-linux/issues/3#issuecomment-1000362157), ran updates and `sof-setup-audio`.
> 
> `aplay -l` returns
> aplay: device_list:276: no soundcards found...
> 
> Here are my other commands if they are needed:
> [dmesg.txt](https://github.com/MilkyDeveloper/cb-linux/files/7791587/dmesg.txt)
> [lsmod.txt](https://github.com/MilkyDeveloper/cb-linux/files/7791589/lsmod.txt)
> [speaker-test.txt](https://github.com/MilkyDeveloper/cb-linux/files/7791591/speaker-test.txt)
> 
> ------------------
> 
> EDIT: 
> After a quick reboot things changed a little bit, here's the updated `aplay -l` info:
> [aplay.txt](https://github.com/MilkyDeveloper/cb-linux/files/7791609/aplay.txt)
> 
> Now the `speaker-test` also runs but still no sound.
> [speaker-test.txt](https://github.com/MilkyDeveloper/cb-linux/files/7791611/speaker-test.txt)
> 
> 

I think if breath is identical to crouton then you can use pulseaudio but not with Mozilla firefox

**Comment by tikverdev** [comment] 2021-12-30 12:00
With pulseaudio I'm getting the option to control volume and output device is showing up as "Analog Output - Comet Lake PCH-LP cAVS" in settings. Neither was happening with alsa. Still no sound though.

**Comment by MilkyDeveloper** [comment] 2021-12-30 14:02
Do not use PulseAudio. Since you have installed it, you have to rerun the script.

**Comment by MilkyDeveloper** [comment] 2021-12-30 14:04
Speaker-test appears to work... Could you post a dmesg after running speaker-test? Also, run alsa-info and answer y when asking for the results to be uploaded. Share the link here.

**Comment by tikverdev** [comment] 2021-12-30 14:25
Rerun the script, rebooted, ran speaker-test.
[dmesg-after.txt](https://github.com/MilkyDeveloper/cb-linux/files/7793296/dmesg-after.txt)

And here's the `alsa-info` http://alsa-project.org/db/?f=7f77096eb08583935b708f9aff4c89bb1e43c4ab

**Comment by MilkyDeveloper** [comment] 2021-12-30 14:50
This is pretty odd. I can't see any errors. Maybe you have something muted, try running:
```
for x in `amixer controls  | grep layback` ; do amixer cset "${x}" on ; done
for x in `amixer controls  | grep layback` ; do amixer cset "${x}" 70% ; done
```

**Comment by tikverdev** [comment] 2021-12-30 15:07
I'm not sure if it's about being muted, in the settings there are no output devices to be selected. 

This is what I get as output when I run the commands. 
[amixer.txt](https://github.com/MilkyDeveloper/cb-linux/files/7793480/amixer.txt)
[amixer70.txt](https://github.com/MilkyDeveloper/cb-linux/files/7793482/amixer70.txt)

Here's what `amixer` is showing after the commands if that helps
[amixerlast.txt](https://github.com/MilkyDeveloper/cb-linux/files/7793500/amixerlast.txt)

http://alsa-project.org/db/?f=3e539d0add94f650053b57a4f345812d3e602a81

**Comment by MilkyDeveloper** [comment] 2021-12-30 15:14
You are relying on your desktop environment, which probably uses PulseAudio rather than ALSA. PulseAudio messes everything up, so it's not supported at the moment. If you run `alsamixer`, you'll find an array of output devices. So running `speaker-test` doesn't produce _any_ speaker output?

**Comment by tikverdev** [comment] 2021-12-30 15:23
Fair point, didn't think of that. Alsamixer does show many output devices but I can only change the volume on Master. Cranking that up to 100 does nothing, `speaker-test` doesn't give any output still.

`aplay -L` output
[aplay.txt](https://github.com/MilkyDeveloper/cb-linux/files/7793582/aplay.txt)

**Comment by MilkyDeveloper** [comment] 2021-12-30 15:27
Try running:
```
speaker-test -Dhw:CARD=sofrt5682,DEV=5 -c 2
```

**Comment by tikverdev** [comment] 2021-12-30 15:30
It's alive! I mean at least there is sound coming from my speakers that is.

**Comment by MilkyDeveloper** [comment] 2021-12-30 15:42
:D Now I just need to find a way to automate this. Try opening `/etc/asound.conf` with a text editor, and find:
```
control {
        name "Master"
        card 0
    }
```
where it says `card 0`, add the line `device 5` under it, so it says:
```
control {
        name "Master"
        card 0
        device 5
    }
```

**Comment by tikverdev** [comment] 2021-12-30 15:48
Done, `speaker-test` outputs no sound and only tries to use "Front Left" speaker.
[asound.txt](https://github.com/MilkyDeveloper/cb-linux/files/7793640/asound.txt)

**Comment by MilkyDeveloper** [comment] 2021-12-30 16:33
Remove `device 5` from `/etc/asound.conf`. Then, run `git clone https://github.com/MilkyDeveloper/cb-ucm.git` and `sudo cp -R cb-ucm/* /usr/share/alsa/ucm2`. After that, run `alsa reload` and test the speakers.

**Comment by tikverdev** [comment] 2021-12-30 18:06
This is what I get when trying to run `alsaucm`
[alsaucm.txt](https://github.com/MilkyDeveloper/cb-linux/files/7794041/alsaucm.txt)
cb-ucm contents are copied succesfully to `/usr/share/alsa/ucm2`, that much I can verify.

`alsa-reload` still reports this:
[alsareload.txt](https://github.com/MilkyDeveloper/cb-linux/files/7794052/alsareload.txt)

Off-topic: to be honest I have poor skills with Linux and bash script in general. Been a Windows guy my whole life due to work and not knowing any better. Recently I have been tempted by the penguin side though... But what I can gather I'm thinking that bash scripting is a lot like PowerShell; great with small tasks but when the scale gets bigger it falls apart. You could do basically everything with both but it's probably not worth it. 
I myself have been learning more python for that sole reason. With it I could achieve most of the time the same results with less hassle. But take my opinion with a big grain of salt and maybe get another one while you're at it lol.

**Comment by MilkyDeveloper** [comment] 2021-12-30 18:14
Try adding the line `Syntax 2` to the top of `/usr/share/alsa/ucm2/sof_rt5682/sof_rt5682.conf`

**Comment by tikverdev** [comment] 2021-12-30 18:26
`alsaucm -c sof_rt5682 set _verb HiFi set _enadev Speaker
ALSA lib main.c:419:(execute_sequence) unable to execute cset 'name='Pin5-Port0 Mux' 1'
ALSA lib main.c:1971:(set_verb_user) error: failed to initialize new use case: HiFi
alsaucm: error failed to set _verb=HiFi: No such file or directory`

**Comment by MilkyDeveloper** [comment] 2021-12-30 18:38
You'll see some lines in `/usr/share/alsa/ucm2/sof_rt5682/HiFi.conf` that contain something like: `Pin*-Port* Mux`. Remove all of those lines.

**Comment by BilalChouaibi** [comment] 2021-12-30 20:30
hello I again need your help. So my wifi/bluetooth card is detected when I put lshw command but it doesn't work

**Comment by BilalChouaibi** [comment] 2021-12-30 20:37
I have that:
  *-network                 
       description: Network controller
       product: Comet Lake PCH-LP CNVi WiFi
       vendor: Intel Corporation
       physical id: 14.3
       bus info: pci@0000:00:14.3
       version: 00
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress msix bus_master cap_list
       configuration: driver=iwlwifi latency=0
       resources: irq:16 memory:d1210000-d1213fff

**Comment by MilkyDeveloper** [comment] 2021-12-30 20:59
How does it “not work”?

**Comment by tikverdev** [comment] 2021-12-31 05:22
> You'll see some lines in `/usr/share/alsa/ucm2/sof_rt5682/HiFi.conf` that contain something like: `Pin*-Port* Mux`. Remove all of those lines, with the asterisks being 1, 2, 3 or 5, 6, 7.

After this `alsaucm -c sof_rt5682 set _verb HiFi set _enadev Speaker` goes through and doesn't output anything. If I run `alsa reload` and try to do `speaker-test` I get this:
[alsa-test.txt](https://github.com/MilkyDeveloper/cb-linux/files/7795385/alsa-test.txt)

If I do a reboot then `speaker-test` runs normallly, but still no sound. I confirmed from `alsamixer` that currently only `sof_rt5682` is listed as soundcard that's in use and it's set as default. Master volume is at 80%.

**Comment by BilalChouaibi** [comment] 2021-12-31 08:50
> How does it “not work”?
![Screenshot from 2021-12-31 08-48-41](https://user-images.githubusercontent.com/84464698/147813294-d343a9d3-f8c4-480f-a2d1-07db1f7d33a5.png)
it say that

**Comment by BilalChouaibi** [comment] 2021-12-31 08:58
[lsmodbilal.txt](https://github.com/MilkyDeveloper/cb-linux/files/7795728/lsmodbilal.txt)
[dmesgbilal.txt](https://github.com/MilkyDeveloper/cb-linux/files/7795729/dmesgbilal.txt)

**Comment by MilkyDeveloper** [comment] 2022-03-16 20:59
I've made a ton of changes to SOF devices since this issue's inception. Maybe trying the script again fro mthe docs would work?

**Comment by MilkyDeveloper** [comment] 2022-03-24 18:51
I also (recently) tested this exact device and audio was working by default :D. I think I'll be closing this. Sorry for the wait.

**Closed by MilkyDeveloper** 2022-03-24 18:51 UTC
Labels: device newer than KBL with SOF
