### ISSUE TITLE
setup crashes

### ISSUE THREAD

**Issue by EMLommers** [cb-linux/breath#151] opened 2022-04-09 16:36 UTC
1) setup crashes with:
E: Invalid operation reinstall

Installation:
FEATURES=ISO,KEYMAP bash ./setup.sh gnome ubuntu bionic-18.04
Host:  Ubuntu 21.10 (impish)

2) build.sh
error: patch failed .gitignore:159
error: patch does does not apply
error: sound/hda/intel-dsp-config.c: No such file or directory
error: sound/soc/sof/sof-pci-dev.c: No such file or directory

and ..

ls: cannot access '.config' : No such file or directory

and.. during compiling: kernel 4.4 (for testing 4.4.302)
no instruction mnemonic suffix given and no register operands : sysret, btr (can be ignored, i think)
drivers/gpu/drm/i915/intel_pm.c warning intel_print_wm_latency (i know i can ignored, i think)

**Comment by MilkyDeveloper** [comment] 2022-04-09 16:44
All of the erorrs in `build.sh` can safely be ignored. You don't need to resetup it, you can just run `bash updatekernel.sh "Absolute path to build.sh"` to update the kernel. In which stage does the setup script crash? What is your host ubuntu version?

**Comment by EMLommers** [comment] 2022-04-09 17:00
Ubuntu 21.10
after setting up tasksel.

**Comment by MilkyDeveloper** [comment] 2022-04-18 14:00
I can't reproduce this, closing.

**Closed by MilkyDeveloper** 2022-04-18 14:00 UTC
