### ISSUE TITLE
No Audio - Acer CB317-1H-C994 (Jasper Lake)

### ISSUE THREAD

**Issue by energy-x** [cb-linux/breath#304] opened 2022-08-12 18:45 UTC
Breath with Ubuntu/gnome. I get the Dummy Output with stock install, tried `sof-setup-audio` and `SOUNDCARD=rtk sof-setup-audio`, which remove the Dummy Output, but do not install a working driver. These configs are from stock install Breath image.
Celeron N4500

HWID: MAGPIE-TQAU C4B-A2C-D4D-Q3C-J8R
Firmware: Google_Magolor.13606.449.0

[lsmod.txt](https://github.com/cb-linux/breath/files/9329216/lsmod.txt)
[alsa.txt](https://github.com/cb-linux/breath/files/9329218/alsa.txt)

**Comment by MilkyDeveloper** [comment] 2022-08-12 19:35
Duplicate of #167

**Closed by MilkyDeveloper** 2022-08-12 19:35 UTC
