### ISSUE TITLE
NAMI Baseboard Support: No Audio working

### ISSUE THREAD

**Issue by death7654** [cb-linux/breath#35] opened 2022-01-10 03:30 UTC
I am on kernel 5.10 with a Dell Insprion Chromebook 14 (7486) Vayne Nami, and no audio even  after i execute the "setup-audio" command. Everything else works, like the touch screen. I am on Ubuntu 21.04

**Comment by MilkyDeveloper** [comment] 2022-01-10 21:52
I'm experiencing the same issue on my Nami. Might take a while for me to get it fixed. A reasonable date might be by around Valentine's Day.

**Comment by death7654** [comment] 2022-01-11 01:57
Take your time. Thank you for working on this, it is really helpful

**Comment by death7654** [comment] 2022-01-11 01:57
I have a feeling that it is with the kernel it self because all the times that i got sound working it only worked on kernels 5.3 and lower it might be a kernel issue.

**Comment by sgulino** [comment] 2022-01-21 17:06
Same issue on an Acer Spin 13, kernel version 5.10, Ubuntu 21.04.

**Comment by death7654** [comment] 2022-02-15 16:21
Should I see if it works?

**Comment by MilkyDeveloper** [comment] 2022-02-15 22:32
Currently I'm more focused over #29 and I'm trying to make a kexec-based bootloader for them. However, that solution won't work for NAMI. This issue has really stumped me even though I developed this project on a NAMI chromebook. I feel that this is really a   kernel issue.

**Comment by death7654** [comment] 2022-02-15 23:35
Gotcha

**Comment by sgulino** [comment] 2022-02-16 16:24
Is there a simple guide to install with an older kernel version? The guided install really only covers using the latest bzimage.

**Comment by MilkyDeveloper** [comment] 2022-02-16 20:22
The oldest kernel that works for audio, 4.4, doesn’t work with Mesa 3D (the intel igpu). I’ll try testing with 4.14.

**Comment by death7654** [comment] 2022-02-16 21:55
Any kernel below 5.4 works from my experience. I might be wrong but I'm pretty sure the "da7219" kernel module was reintroduced in 5.4

**Comment by death7654** [comment] 2022-02-23 21:43
Nami just got the 5.4 kernel upgrade in the beta channel. I'm gonna use the sound on kabylake github issue and put all the firmware in breath and see if I can get sound to work

**Comment by death7654** [comment] 2022-02-24 04:04
It didn't work

**Comment by MilkyDeveloper** [comment] 2022-03-20 16:11
Audio has been fixed with NAMI, follow the updated docs and enjoy :D

**Closed by MilkyDeveloper** 2022-03-20 16:11 UTC

**Comment by death7654** [comment] 2022-03-20 17:52
> Audio has been fixed with NAMI, follow the updated docs and enjoy :D

Thank you so much

**Comment by ArtemPozharov** [comment] 2022-03-22 18:17
It's impossible to install Breath on Nami. I selected the /dev/mmcblk0. Firstly, the system warns that this bucket is used in runtime. Snap apps don't work (SELinux dorsn't allow one) , setup-audio can't finish the sound fix due to /mnt mount error. I try this since December. No changes with the new release.

**Comment by MilkyDeveloper** [comment] 2022-03-22 18:21
What "/mnt mount error"? Could you show me the exact output of the command? Note that you need to have a ChromeOS install on the internal disk first, and only then can you run `setup-audio`. I personally have a `NAMI` device and everything is working prefectly for me.

**Comment by ArtemPozharov** [comment] 2022-03-22 19:53
> What "/mnt mount error"? Could you show me the exact output of the command? Note that you need to have a ChromeOS install on the internal disk first, and only then can you run `setup-audio` once booted from the USB. I personally have a `NAMI` device and everything is working prefectly for me.

I fellow your advice. I got a new error after setup-audio. ![IMG_20220322_203451.jpg](https://user-images.githubusercontent.com/50730813/159564368-8d46ffea-e3d2-40ed-a205-39cb03a912b0.jpg)

**Comment by MilkyDeveloper** [comment] 2022-03-22 19:59
Run `rm -rf /usr/share/alsa/ucm2/kblda7219max` and then rerun the script.

**Comment by ArtemPozharov** [comment] 2022-03-22 21:27
> Run `rm -rf /usr/share/alsa/ucm2/kblda7219max*` and then rerun the script.
The problem remains
![IMG_20220322_222611.jpg](https://user-images.githubusercontent.com/50730813/159578841-dbc7e1be-487f-4a34-920f-0bf9209209ff.jpg)

**Comment by MilkyDeveloper** [comment] 2022-03-22 21:31
Run `sudo umount /mnt` and the rm command.

**Comment by ArtemPozharov** [comment] 2022-03-22 21:38
> Run `sudo umount /mnt` and the rm command.

I ran these two command and then reran the setup-audio script. It returned me to the initial problem. 
![IMG_20220322_223804.jpg](https://user-images.githubusercontent.com/50730813/159580527-90cda5a4-b80f-4ef9-a595-ccce7b2287f3.jpg)

**Comment by death7654** [comment] 2022-03-22 22:18
Try a newer distro, the current distro you are currently using uses the old ucm format

**Comment by ArtemPozharov** [comment] 2022-03-22 22:26
I created this directory manually, reran the script, got a success notification, but I still don't hear the sound.

**Comment by ArtemPozharov** [comment] 2022-03-22 22:28
> Try a newer distro, the current distro you are currently using uses the old ucm format

Thanks. Should I try Ubuntu 22.04?

**Comment by death7654** [comment] 2022-03-22 22:37
Sure, idk if its out yet though. Ubuntu 21.04 and higher should work

**Comment by ArtemPozharov** [comment] 2022-03-22 22:39
I use Ubuntu 21.10...

**Comment by ArtemPozharov** [comment] 2022-03-22 22:48
> Sure, idk if its out yet though. Ubuntu 21.04 and higher should work

Please, tell me about your recipe to working audio. 
What is your distro? Did you use FEATURE=ISO or write an OS to USB stick directly?

**Comment by death7654** [comment] 2022-03-22 22:53
Well, I am currently trying to get audio to work in uefi, and read everything before you do anything, you have one more step before writing it to a USB. The iso should work fine

**Comment by MilkyDeveloper** [comment] 2022-03-22 22:58
@ArtemPozharov Just try everything on the docs, from scratch, one more time :D. I can confirm that this script works on a fresh install.

**Comment by ArtemPozharov** [comment] 2022-03-22 23:01
> @ArtemPozharov Just try doing everything on the docs, from scratch, one more time :D. I can confirm that this script works on a fresh install.

Ok, I will try. Thanks for attention. I'll tell about success!

**Comment by ArtemPozharov** [comment] 2022-03-23 14:46
Please, look at https://github.com/cb-linux/breath/issues/117
